version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: quiz-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=quizadmin
      - MONGO_INITDB_ROOT_PASSWORD=quizpassword
    restart: unless-stopped

volumes:
  mongo-data:
